logging:
  level:
    org.eclipse.jetty: warn
    org.springframework.boot.web: warn
    org.springframework.web: warn
    vn.kihon: info

server:
  address: "kihon.vn"  # comment this to expose us to outside
  compression:
    enabled: true
  port: 8888
  ssl:
    enabled: true # force https
    key-alias: "kihon.vn"
    key-store: "classpath:kihon-vn.p12"
    key-store-password: "123456"

spring:
  main:
    banner-mode: off