version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order
    ports:
      - 9091:3306
    volumes:
      - ./db/mysql:/var/lib/mysql