version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: utility
    ports:
      - 9090:5432
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data